version: '3.8'

services:
  task-manager:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  tests:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: pytest tests/ -v --cov=app